/* Copyright (c) 2017-2026, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "roq/core/json/buffer_stack.hpp"

#include "roq/lighter/protocol/json/order_book_details_ack.hpp"

using namespace roq;
using namespace roq::lighter;

using namespace std::literals;
using namespace std::chrono_literals;

using value_type = protocol::json::OrderBookDetailsAck;

// note! truncated
TEST_CASE("simple", "[order_book_details_ack]") {
  auto message = R"({)"
                 R"("code":200,)"
                 R"("order_book_details":[{)"
                 R"("symbol":"NBIS",)"
                 R"("market_id":189,)"
                 R"("market_type":"perp",)"
                 R"("base_asset_id":0,)"
                 R"("quote_asset_id":0,)"
                 R"("status":"active",)"
                 R"("taker_fee":"0.0000",)"
                 R"("is_taker_fee_enabled":true,)"
                 R"("maker_fee":"0.0000",)"
                 R"("is_maker_fee_enabled":true,)"
                 R"("liquidation_fee":"1.0000",)"
                 R"("min_base_amount":"0.0250",)"
                 R"("min_quote_amount":"10.000000",)"
                 R"("order_quote_limit":"10000000.000000",)"
                 R"("supported_size_decimals":4,)"
                 R"("supported_price_decimals":2,)"
                 R"("supported_quote_decimals":6,)"
                 R"("created_at":"1780590039878",)"
                 R"("multiplier":"1.000000000000000000",)"
                 R"("start_timestamp":0,)"
                 R"("end_timestamp":0,)"
                 R"("outcome":0,)"
                 R"("operator_account_index":1,)"
                 R"("settlement_cap":0,)"
                 R"("settlement_type":0,)"
                 R"("settlement_price":0,)"
                 R"("default_price":0,)"
                 R"("is_frozen":false,)"
                 R"("size_decimals":4,)"
                 R"("price_decimals":2,)"
                 R"("quote_multiplier":1,)"
                 R"("default_initial_margin_fraction":1000,)"
                 R"("min_initial_margin_fraction":1000,)"
                 R"("maintenance_margin_fraction":600,)"
                 R"("closeout_margin_fraction":400,)"
                 R"("mark_price":"241.58",)"
                 R"("index_price":"241.34",)"
                 R"("last_trade_price":241.57,)"
                 R"("daily_trades_count":4967,)"
                 R"("daily_base_token_volume":7092.3134,)"
                 R"("daily_quote_token_volume":1705316.548081,)"
                 R"("daily_price_low":234.06,)"
                 R"("daily_price_high":247.03,)"
                 R"("daily_price_change":2.490453966907085,)"
                 R"("open_interest":4242.3391,)"
                 R"("daily_chart":{},)"
                 R"("market_config":{)"
                 R"("market_margin_mode":0,)"
                 R"("insurance_fund_account_index":281474976710654,)"
                 R"("liquidation_mode":0,)"
                 R"("force_reduce_only":false,)"
                 R"("trading_hours":"",)"
                 R"("funding_fee_discounts_enabled":false,)"
                 R"("hidden":false,)"
                 R"("rfq_enabled":true)"
                 R"(},)"
                 R"("strategy_index":5,)"
                 R"("market_flags":0,)"
                 R"("funding_premium_multiplier":50,)"
                 R"("funding_clamp_small":"0.0500",)"
                 R"("funding_clamp_big":"4.0000",)"
                 R"("base_interest_rate":"0.0032")"
                 R"(},{)"
                 R"("symbol":"XAU",)"
                 R"("market_id":92,)"
                 R"("market_type":"perp",)"
                 R"("base_asset_id":0,)"
                 R"("quote_asset_id":0,)"
                 R"("status":"active",)"
                 R"("taker_fee":"0.0000",)"
                 R"("is_taker_fee_enabled":true,)"
                 R"("maker_fee":"0.0000",)"
                 R"("is_maker_fee_enabled":true,)"
                 R"("liquidation_fee":"1.0000",)"
                 R"("min_base_amount":"0.0015",)"
                 R"("min_quote_amount":"10.000000",)"
                 R"("order_quote_limit":"5000000.000000",)"
                 R"("supported_size_decimals":4,)"
                 R"("supported_price_decimals":2,)"
                 R"("supported_quote_decimals":6,)"
                 R"("created_at":"1760970336561",)"
                 R"("multiplier":"1.000000000000000000",)"
                 R"("start_timestamp":0,)"
                 R"("end_timestamp":0,)"
                 R"("outcome":0,)"
                 R"("operator_account_index":1,)"
                 R"("settlement_cap":0,)"
                 R"("settlement_type":0,)"
                 R"("settlement_price":0,)"
                 R"("default_price":0,)"
                 R"("is_frozen":false,)"
                 R"("size_decimals":4,)"
                 R"("price_decimals":2,)"
                 R"("quote_multiplier":1,)"
                 R"("default_initial_margin_fraction":666,)"
                 R"("min_initial_margin_fraction":400,)"
                 R"("maintenance_margin_fraction":240,)"
                 R"("closeout_margin_fraction":160,)"
                 R"("mark_price":"4191.83",)"
                 R"("index_price":"4188.61",)"
                 R"("last_trade_price":4192.1,)"
                 R"("daily_trades_count":40870,)"
                 R"("daily_base_token_volume":7430.3208,)"
                 R"("daily_quote_token_volume":31022579.056951,)"
                 R"("daily_price_low":4146.09,)"
                 R"("daily_price_high":4205.79,)"
                 R"("daily_price_change":0.8515276487827413,)"
                 R"("open_interest":4351.1726,)"
                 R"("daily_chart":{},)"
                 R"("market_config":{)"
                 R"("market_margin_mode":0,)"
                 R"("insurance_fund_account_index":281474976710654,)"
                 R"("liquidation_mode":0,)"
                 R"("force_reduce_only":false,)"
                 R"("trading_hours":"",)"
                 R"("funding_fee_discounts_enabled":false,)"
                 R"("hidden":false,)"
                 R"("rfq_enabled":true)"
                 R"(},)"
                 R"("strategy_index":3,)"
                 R"("market_flags":0,)"
                 R"("funding_premium_multiplier":50,)"
                 R"("funding_clamp_small":"0.0500",)"
                 R"("funding_clamp_big":"4.0000",)"
                 R"("base_interest_rate":"0.0032")"
                 R"(})"
                 R"(],)"
                 R"("spot_order_book_details":[{)"
                 R"("symbol":"SKY/USDC",)"
                 R"("market_id":2053,)"
                 R"("market_type":"spot",)"
                 R"("base_asset_id":8,)"
                 R"("quote_asset_id":3,)"
                 R"("status":"active",)"
                 R"("taker_fee":"0.0000",)"
                 R"("is_taker_fee_enabled":true,)"
                 R"("maker_fee":"0.0000",)"
                 R"("is_maker_fee_enabled":true,)"
                 R"("liquidation_fee":"0.0000",)"
                 R"("min_base_amount":"100",)"
                 R"("min_quote_amount":"10.000000",)"
                 R"("order_quote_limit":"281474976.710655",)"
                 R"("supported_size_decimals":0,)"
                 R"("supported_price_decimals":6,)"
                 R"("supported_quote_decimals":6,)"
                 R"("created_at":"1768058911384",)"
                 R"("multiplier":"1.000000000000000000",)"
                 R"("start_timestamp":0,)"
                 R"("end_timestamp":0,)"
                 R"("open_interest":"0.000000",)"
                 R"("outcome":0,)"
                 R"("operator_account_index":1,)"
                 R"("settlement_cap":0,)"
                 R"("settlement_type":0,)"
                 R"("settlement_price":0,)"
                 R"("default_price":0,)"
                 R"("is_frozen":false,)"
                 R"("size_decimals":0,)"
                 R"("price_decimals":6,)"
                 R"("last_trade_price":0.081834,)"
                 R"("daily_trades_count":108,)"
                 R"("daily_base_token_volume":79522,)"
                 R"("daily_quote_token_volume":6775.1459620000005,)"
                 R"("daily_price_low":0.081385,)"
                 R"("daily_price_high":0.092894,)"
                 R"("daily_price_change":-11.905095109426975,)"
                 R"("daily_chart":{})"
                 R"(},{)"
                 R"("symbol":"LDO/USDC",)"
                 R"("market_id":2054,)"
                 R"("market_type":"spot",)"
                 R"("base_asset_id":9,)"
                 R"("quote_asset_id":3,)"
                 R"("status":"active",)"
                 R"("taker_fee":"0.0000",)"
                 R"("is_taker_fee_enabled":true,)"
                 R"("maker_fee":"0.0000",)"
                 R"("is_maker_fee_enabled":true,)"
                 R"("liquidation_fee":"0.0000",)"
                 R"("min_base_amount":"5.0",)"
                 R"("min_quote_amount":"10.000000",)"
                 R"("order_quote_limit":"281474976.710655",)"
                 R"("supported_size_decimals":1,)"
                 R"("supported_price_decimals":5,)"
                 R"("supported_quote_decimals":6,)"
                 R"("created_at":"1768058911386",)"
                 R"("multiplier":"1.000000000000000000",)"
                 R"("start_timestamp":0,)"
                 R"("end_timestamp":0,)"
                 R"("open_interest":"0.000000",)"
                 R"("outcome":0,)"
                 R"("operator_account_index":1,)"
                 R"("settlement_cap":0,)"
                 R"("settlement_type":0,)"
                 R"("settlement_price":0,)"
                 R"("default_price":0,)"
                 R"("is_frozen":false,)"
                 R"("size_decimals":1,)"
                 R"("price_decimals":5,)"
                 R"("last_trade_price":0.4803,)"
                 R"("daily_trades_count":13,)"
                 R"("daily_base_token_volume":2753.4,)"
                 R"("daily_quote_token_volume":1272.629626,)"
                 R"("daily_price_low":0.45438,)"
                 R"("daily_price_high":0.4803,)"
                 R"("daily_price_change":1.0030912876159233,)"
                 R"("daily_chart":{})"
                 R"(})"
                 R"(])"
                 R"(})"sv;
  auto helper = [](value_type const &obj) {
    CHECK(obj.code == 200);
    REQUIRE(std::size(obj.order_book_details) == 2);
    REQUIRE(std::size(obj.spot_order_book_details) == 2);
    //
  };
  core::json::BufferStack buffers{8192, 1};
  value_type obj{message, buffers};
  helper(obj);
}
